### ISSUE TITLE
pip install edflow fails on clean conda environment

### ISSUE THREAD

**Issue by jhaux** [pesser/edflow#142]
**Describe the bug**
I ran `pip install edflow` and got the following error
```
(abc_q) jhaux@quadxeon5:~/work_projects/abc_pose/abc_pose/data$ pip install edflow                                                       
20170516                                                                                                                                 
Collecting edflow                                                                                                                        
  Downloading https://files.pythonhosted.org/packages/03/36/973530958128065a09d53e84b8e4d8638d6b12e50c975c45987e544eae97/edflow-0.2.1-py3-none-any.whl (93kB)                                                                                                                     
     |████████████████████████████████| 102kB 2.1MB/s                                                                                    
Collecting pyyaml (from edflow)                                                                                                          
  Using cached https://files.pythonhosted.org/packages/e3/e8/b3212641ee2718d556df0f23f78de8303f068fe29cdaa7a91018849582fe/PyYAML-5.1.2.tar.gz                                                                                                                                     
Collecting scikit-learn (from edflow)                                                                                                    
  Downloading https://files.pythonhosted.org/packages/1e/ce/9d8c88e68af0a5b5c5d78d8d2b7bcadfd45e1d6afc863ccb9aee30765b06/scikit-learn-0.21.3.tar.gz (12.2MB)                                                                                                                      
     |████████████████████████████████| 12.2MB 6.7MB/s                                                                                   
Collecting tqdm (from edflow)                                                                                                            
  Downloading https://files.pythonhosted.org/packages/02/56/60a5b1c2e634d8e4ff89c7bab47645604e19658f448050a21facffd43796/tqdm-4.33.0-py2.py3-none-any.whl (50kB)                                                                                                                  
     |████████████████████████████████| 51kB 3.7MB/s                                                                                     
Collecting chainer (from edflow)                                                                                                         
Collecting fastnumbers (from edflow)                                                                                                     
  Downloading https://files.pythonhosted.org/packages/15/3f/80483ecd647f2f83ef355f669eacf712aa437ec1196150d2e8b1e87e1c95/fastnumbers-2.2.1.tar.gz (365kB)                                                                                                                         
     |████████████████████████████████| 368kB 23.5MB/s                                                                                   
Collecting numpy (from edflow)                                                                                                           
  Downloading https://files.pythonhosted.org/packages/da/32/1b8f2bb5fb50e4db68543eb85ce37b9fa6660cd05b58bddfafafa7ed62da/numpy-1.17.0.zip (6.5MB)                                                                                                                                 
     |████████████████████████████████| 6.5MB 21.7MB/s                                                                                   
Collecting scikit-image (from edflow)                                                                                                    
  Downloading https://files.pythonhosted.org/packages/e0/46/ca035f5d7d3414124a3a5ef22cd2e75c0c5149042a668375f1d44eb69f8f/scikit-image-0.15.0.tar.gz (32.3MB)                                                                                                                      
     |████████████████████████████████| 32.3MB 25.6MB/s                                                                                  
    ERROR: Complete output from command python setup.py egg_info:                                                                        
    ERROR: Traceback (most recent call last):                                                                                            
      File "<string>", line 1, in <module>                                                                                               
      File "/tmp/pip-install-h3vb6_n4/scikit-image/setup.py", line 31, in <module>                                                       
        from numpy.distutils.command.build_ext import build_ext                                                                          
    ModuleNotFoundError: No module named 'numpy'                                                                                         
    ----------------------------------------                                                                                             
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-h3vb6_n4/scikit-image/                            
```

**To Reproduce**
```
conda create -n abc_q python ipython jupyter 
conda activate abc_q
pip install edflow
```

**Desktop (please complete the following information):**
 - I ran all commands on the IWR servers

**Comment by conrad784** [comment]
> IWR servers
Which server did you run it on?

```Collecting scikit-image (from edflow)                                                                                                                                                        
  Downloading https://files.pythonhosted.org/packages/2e/21/ea56c8bb2e8112837dd71aebeb2ac67913e784911c0d7f493a593fa1a207/scikit_image-0.15.0-cp37-cp37m-manylinux1_x86_64.whl (26.3MB)       
     |████████████████████████████████| 26.3MB 22.9MB/s                                                                                                                                      
```
My run on hgsgpu is getting `manylinux1` versions, whereas your run got `none` packages -- but what exactly changes this behavior.

I'd say, this is not a problem of the package, but of the conda environment.

**Comment by conrad784** [comment]
This must be a pip error, I am running pip 19.2.2.
The resulting list:
```
(abc_q) xxx@hgsgpu01:~$ python -c "from pip._internal import pep425tags; print(pep425tags.get_supported())"
[('cp37', 'cp37m', 'manylinux2010_x86_64'), ('cp37', 'cp37m', 'manylinux1_x86_64'), ('cp37', 'cp37m', 'linux_x86_64'), ('cp37', 'abi3', 'manylinux2010_x86_64'), ('cp37', 'abi3', 'manylinux1_x86_64'), ('cp37', 'abi3', 'linux_x86_64'), ('cp37', 'none', 'manylinux2010_x86_64'), ('cp37', 'none', 'manylinux1_x86_64'), ('cp37', 'none', 'linux_x86_64'), ('cp36', 'abi3', 'manylinux2010_x86_64'), ('cp36', 'abi3', 'manylinux1_x86_64'), ('cp36', 'abi3', 'linux_x86_64'), ('cp35', 'abi3', 'manylinux2010_x86_64'), ('cp35', 'abi3', 'manylinux1_x86_64'), ('cp35', 'abi3', 'linux_x86_64'), ('cp34', 'abi3', 'manylinux2010_x86_64'), ('cp34', 'abi3', 'manylinux1_x86_64'), ('cp34', 'abi3', 'linux_x86_64'), ('cp33', 'abi3', 'manylinux2010_x86_64'), ('cp33', 'abi3', 'manylinux1_x86_64'), ('cp33', 'abi3', 'linux_x86_64'), ('cp32', 'abi3', 'manylinux2010_x86_64'), ('cp32', 'abi3', 'manylinux1_x86_64'), ('cp32', 'abi3', 'linux_x86_64'), ('py3', 'none', 'manylinux2010_x86_64'), ('py3', 'none', 'manylinux1_x86_64'), ('py3', 'none', 'linux_x86_64'), ('cp37', 'none', 'any'), ('cp3', 'none', 'any'), ('py37', 'none', 'any'), ('py3', 'none', 'any'), ('py36', 'none', 'any'), ('py35', 'none', 'any'), ('py34', 'none', 'any'), ('py33', 'none', 'any'), ('py32', 'none', 'any'), ('py31', 'none', 'any'), ('py30', 'none', 'any')]
```

This decides which version gets loaded from pypi [see here](https://stackoverflow.com/questions/37793046/how-does-pip-decide-which-many-linux-wheel-to-use).
For me, this gets the wheel packages for manylinux1, for @jhaux it seems to always pull the source packages because it is the first match (i.e. no match).
